BBBB BBBBBBBBBBB BBBBBBBBBB

BB BBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX X
                  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXX XXX X XXXX XXXX XXXXXXXX XXXXX XXX XXXXXXXX XXXXX XXXXXX
                XXXXXXXXX XXXXXXXX XXX XXXXX XXXXXX XX XXX XXXXXXXX XX  XXXXXXXX XXXXXXXX
              XXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXX XXXX
        XXXXX XXX XXXXXXXX XXXXX X XXX BB BBB BBBBBBBBBBBB XXXXXXXXXX BBBBB
            XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX X XXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX
            XX XXXX XXXX XXXX XXXXXX XXX XX XXXXXXXXXXX XXX XXXX XXX XX XXXXXX XXXXXXXXXX XXXXX XX XXXX XXXXXXXXXXXX
            XXXXXXXXXX XXXXXX XX XXXXXXXXXXXXXX XXXXXXXXX XX XX XXXXXXXXXXX XX XXXXX XXXXXX XX XX XXXXXXXX XXXXXXX


        XXXXXXXXXXXXXXXXXXXXXXXXXXXX

BBBB
XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXX XXXXXXXXXXXX XXXX X XX XXXXXXXXXXXXXXXXX XXXXXX XXX 
                XXXXXXXXX XXXXXX XXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX


BBBBB