BBBB BBBBBBBBBBB BBBBBBBBBB
 XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXX XXX XX XXX XXXXXXXXXXXXXXXX XXXXXXXXX XX XXX XXXXXXXXX XXX XX XXXXXXXXXX
                    XX XXXXXXXX XXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXX
                XX XXXXXXXXXXXXXXXXXX XX XX XXXX XX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX X XXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXX XXXX XX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XX XXXXXX
                    XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXX

                XX XXXXXXXXXXXXXXXXXX
                    X XXXX XXXXXX XXXXXXX X XXXX XXXXXXXXXXX XXX XXXXX XX XXXXXXXXXXXX XXX XXXXXX XX XXXXXXXXX XXXXXXXXXXX
    BB BBBBBBBBBBBB
    XX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XX XXXXXXXXX XXXXXX XXXXXXXXXX XXXX XXXXXXXXX XXX XX XXXXXXXXXXXXXXX XXX XX XXXXXXXXXXXX
XXXX

                BBBBB
                XX XXXXXXXXXXXXXXXXXXXX XXXX XX XXX XXXXXXXXXXXX XX XXXXXXXX XXXXXXX XXX XXXXXXXXXXXXXX
                    XX XXXX XXX XX XXXX XXXXXXXX XXXXXXX XXXXXXXXXXX XX XXX XX XXXX XX XXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX

        XXXXXX
 XXXXXX


