BBBB BBBBBBBBBBB BBBBBBBBBB

BB BBBBBBBBBBBB
    XXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXX XX XXXXXXXXXXXX XXXXXXXXX XX XXX XXXXXXXXXXX XX XX XXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
    XX XXXX XXXX XXX XXXXXX XXXXXXX XX XXXXXXXXXXX XXX XXXX XXX XX XXXXXX XX XXX XXXXX XXX XXX XXXXXXXXXXXXX
        XX XXXXXXXX XXX XXXX XXXX XXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                  XX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXXXX
            XXXXXX
      XXXXXX
BBBB BBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXX XXX X XXXX XXXX XXXXXXXX XXXXX XXX XXXXXXXX XXXXX XXXXXX
                XXXXXXXXX XXXXXXXX XXX XXXXX XXXXXX XX XXX XXXXXXXX XX  XXXXXXXX XXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX XXX
                  XX XXX XXXXXXXX XXXXX X XXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX X XXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX
            XX XXXX XXXX XXXX XXXXXX XXX XX XXXXXXXXXXX XXX XXXX XXX XX XXXXXX XXXXXXXXXX XXXXX XX XXXX XXXXXXXXXXXX
            XXXXXXXXXX XXXXXX XX XXXXXXXXXXXXXX XXXXXXXXX XX XX XXXXXXXXXXX XX XXXXX XXXXXX XX XX XXXXXXXX XXXXXXX XXXX
              XXXXXX
            XXXXXX
        XXXXXXXXXXXX

BBBBB


