BBBB BBBBBBBBBBB BBBBBBBBBB
XXXX XXXXXXXXXXXXXX
    XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXX XXXXXXXXXXXXXXXXXX
          XXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXX
