XXXXXX XXXXXXXXXXXXXXXX
XXXXXXXXXXXX X
    XXXXXXXXXX
    XXXXXXXXXXX
X
XXXXXXXX


XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
XXXX
XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXX
XX XXXX XX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXX

XXXXXX


XXXX  XXXX XX XXXXXX XX XXX XXXX XX XXX XXXXXXXXX XX XXX XXXXX XX XXX XXXXXX X XXX
XXXX XXXXXXX
XXXX    BB BBBBBBBBBB BB BBBBBB BBBBBBBBBB BBBBBBBBBB BBBBBBBBBXXX
XXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX
XXXX  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX        XXXX XXXXXX XX  XXX XXXX XXXXXXXXX
XXXX    XXXXXXXXX
XXXX      BBBBXXX
XXXX    BBBBBXXX
XXXXXXXXXXXX

XXXXX