BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB BBBBBBBBBB

BBBBB BBBBB
    XXXXXXXXXXX XXXXXX
BBBBBBBB

BBBBB BBBBBBB

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXX XXXX XXXXXXXXXXXXXXX XXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXX

				X
			X

			XXXXXXXX XXXXXXXXXXXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXX XXXX XXXXXXXXXXXXXXX XXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXX

				X
			X
			XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
          XX XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXX
          X XXXX X
            XXXXXXXXXXXX
          X
        X

                XXXXXXXX XXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXX X XX
      XXX XXXX XXXX XXXXXXXXXXXXXXXXXXXX XXXX X
        XX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX XXX XXXXX X
          XXXXXXXX
        X
      X
      XXXXXXXX X X XX XXXXXXXXXXXXXXXXX XXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX
     X
      XXXXX
         XXXXXXXXXXXXXXXXXXXXXXXX
      X

      XXXXXXXXXXXXXXXXXXX

        X
		XXXXXXXXXBBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
BB BBBBBBBBBBBBBBBBBBB BB B
    BBB BBBBB BB BBBB
        BB BBBBBBBBBB BB BBBBBBBBBB

             XXX
                    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XX XXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX X XXXX XX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XX XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XX XX XXXXXXXXXX XX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXX XXXXX XXXXXX XX XX XX XXXXXXXXXX XX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXX XX XXXXXXXXXXXXXXXXX

                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX X XXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

                           XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX

        BBBB BBBBBBBBBB BB BBBBBBBBBBB

            BBBBBBBBB BBBBB

        BBBBB
    BBBBBB

BBBB BBBBBBBBBBBBBBBBBBB BB B

    BBB BBBBB BB BBBB
        BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB

         XXX
        
            XXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XX
            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX X XXXX

        XXXX
        BBBBB
    BBBBBB

BBBB BBBBBBBBBBBBBBBBBBB BB B

        BBB BBBBB BB BBBB

        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXX
            XXXX XXXXX
            XXXXXXXX
            XXXXXXX XXXX
                XXX XXXXXXXXXXXX
                    XXXXXXXXXX XXXX XXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                XXX XXXXXXXXXXXX
                    XXXXXXXX XXX XXXXXXXXXXX
            XXXXX
            XXXXXXXX

        XXXXXXXX

        BBBBBB


BBBB BBBBBBBBBBBBBBBBBBB BB BB BB  BBBBBBBBBBBBBBBBBBB BB BB


            XX XXXXXXXX XXXX X XXX XXXX XXX XXXXXXXXXXXX XXXXXXXXXXX    XXXX
        BBB BBBBB BB BBBB

        XXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
            XXXX
                BB  BBBBBBBBBBBBBBB  BB BXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXX
                BBBBB

            XXXXX

            XXXX
                XXX XXXXXXXXXXXX
                    
                    
                XXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXX XXX XXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX

            XXXXX

        XXXXXXXX

        BBBBBB

BBBB
                BBB BBBBB BB BBBB

                        BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB

                XXXX XXXXXXXXXXX XXXXXXXXXX  X
                    XX XXXXXXXX XX XXXXXXXXXXXXXXXX XXXX XXX XXXXXXXXX XXX XXXXXXX
                    XX XXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX
                    XXXXX XXXXXXXXX XXX XXXXXXX XXX XXXXXXX
                    XXXXXXX XXXXXXX XX XX XXXXXXX XXXXX XX XXXXXXXXXX XXXX XX XXXXXXXXXXX XXX XX XXXXXXXXX XXX XX XXXXXXXXXX

                XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX X
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXX
                                                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX X XXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX X XXXXX XXX XXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXXXXXXXXXXX

                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                           XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX


            XXXX
                        BBBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBB
                        XXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
BBBB BBBBBBBBBB BB BBBBBBB BB BBBBBBBBBB BB BBBBBBBB

        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX X
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX
                        BBBB BBBBBBBBBB BB BBBBBBBBBBBBBBBB
                        XXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXX
                        BBBB BBBBBBBBBB BB BBBBBBBBBB
                        XXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


                        BBBB
                            BBBBBBBBB BBBBB
BBBBB
            BBBBBB

BBBBB


    XXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBB BB BB
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
     XXX XXXXXXXXX XXXX XXXX XX XXXXXXXX XXX XXX XXXXXXXXXX XXXXXXX
       XXXXXXX XXXXX X XXXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXX XXX XX XXXXX XXXXXX XXX XXXXXX XXX XXXXXXX XXX X XXXXXXXX
       XXXXXXXXXX X XXXXXX XXXXX XXXX XXX XXXXXXXXX XXX XXXX X XXX XXXXXX XXXXXX XXXX
       XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     XXXX
     XXXXXX
BBBBBXXXXXX


BB BBBBBBBBBBBBBBBBBBB BB B
XXXXXXX XXXXXXXXXXXXXXXXXX  XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXX
BBBB
XXXXXXX XXXXXXXXXXXXXXXXXX  XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX  X XXXXXXXX XXXXXXXXX
BBBBB

BBBBBBBB