BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBB
    

    BB BBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    BBBBB

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX X
            XXXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
        X
        XXXXXXXX XXXXXXXXXXXXXXXXX X
            XXX XXX X XXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXX XXXXXXXXX
        X
        XXXXXXXXXXXX X
            BB BBBBBBBBBBBBBBBBBBBBBBBB
                XXX XXXXXXXX X XX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                        XXXX X X
                            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX X
                                XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
                                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                            XXXXXXXXX X
                        XXXXXX X
                    XXXXXXXX
                XX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXX X XXX XXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXX X FFFFFFFFX
                XXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX X
                        XX XXX XX XXXXXX XXXXX XX XXXXXXX XXXX XXX XXXX XXXXXXXXXXX
                        XX XX XX XXXXXXX XXXX
                        XXX XXXXXX X XXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX
                    XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX X
                        XXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXX
                        XXXXXXXXXXXXXXXXXXXX
                        XX XXXX XXX XXXXXX XXXX
                        XX XXXX XXXXX XXXXXXX XXXXXXX
                        XXX XXXXXXXXXXXX X XXXXX X XX X XXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX
            BBBBB
        XXX
    XXXXXXXXX
BBBBBBBB

BBBBB BBBBB
    
BBBBBBBB